openapi: "3.0.0"

info:
  version: 1.0.2
  title: black-list-api
  description: OpenAPI for black listed persons

server:
  -url: http://lockalhost:8080/api
  description: Local server

paths:
  /blackListedPersons:
    get:
      summary: Returns list of all black listed persons
      operationId: listWithBlackListedPersons
      tags:
        - blackListedPersons
      parameters:
        - name: limit
          in: query
          description: Limits the number of items on a page
          schema:
            type: integer
        - name: offset
          in: query
          description: Specifies the page number of the black listed persons to be displayed
          schema:
            type: integer
      responses:
        '200':
          description: Successfully returned a list with black listed persons
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlackListedPersonDTO'

  /blackListedPerson:
    post:
      summary: Save BlackListedPerson
      operationId: saveBlackListedPerson
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlackListedPersonDTO'
    responses:
      '200':
        description: Black listed person created successfully
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlackListedPersonDTO'


  /blackListedPersons/{blackListedPersonId}:
    get:
      summary: Returns black listed person by ID.
      operationId: getBlackListedPersonById
parameters:
  - name: id
    in: path
    description: Unique ID of the person
    required: true
    schema:
      type: string
      format: uuid
    responses:
      '200':
        description: Done
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlackListedPersonDTO'

components:
  schemas:
    BlackListedPersonDTO:
      type: object
      description: Blacklisted person Data
      properties:
        id:
          type: string
          format: uuid
        personFirstName:
          type: string
        personLastName:
          type: string
        personCode:
          type: string
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string

