version: '1'

networks:
  javaguru:

services:
  message-broker:
    networks: [javaguru]
    container_name: rabbitmq-container
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    networks: [javaguru]
    container_name: mysql-container
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: insurance-calc
    ports:
      - "3000:3306"

  web:
    networks: [javaguru]
    container_name: insurance-calc-container
    image: insurance-calculator:1.0.3
    ports:
      - "8080:8080"
    depends_on:
      - db
      - message-broker

  doc-generator:
     networks: [javaguru]
     container_name: doc-generator-container
     image: doc-generator:1.0.2
     ports:
       - "8888:8888"
     depends_on:
       - message-broker