version: '1'

networks:
  javaguru:

services:
  db:
    networks: [javaguru]
    container_name: mysql-container
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: insurance-calculator-db
    ports:
      - "3000:3306"

  insurance-calculator-app:
    networks: [javaguru]
    container_name: insurance-calc-container
    image: insurance-calculator:1.0.2
    ports:
      - "8080:8080"
    depends_on:
      - db
